### ISSUE TITLE
bad certificate on playground

### ISSUE THREAD

**Issue by martilidad** [M4GNV5/PointerScript#5]
The certificate delivered is not valid for pointerscript.org.

**Comment by M4GNV5** [comment]
Hey,

Looks like i forgot the domain in my certificate script.
It is now fixed.

Also the playground is broken. There used to be a websocket backend which ran the code in a linux container.
Maybe compiling PointerScript to WASM using emcscripten would be the way to go in the future :thinking:. That requires libjit to work with emcscripted though. Also `dlopen`/`dlsym` probably wont be available.

Anyways, thanks for reporting this.
